apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: intel-qat-plugin
spec:
  template:
    spec:
      containers:
      - name: intel-qat-plugin
        args:
        - "-max-num-devices=128"
        #- "-v=4"
